### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
content-type: application/json

{
"nome": "Administrador",
"matricula": "001",
"cpf": "11111111111",
"telefone": "49999999999",
"grupo": 1,
"senha": "123456"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1
content-type: application/json

{
"nome" : "Kadu Farias",
"matricula" : "lu12353",
"cpf" : "12345678905",
"telefone" : "tel2383738",
"grupo" : 1,
"senha" : "dc7378a6b6316017b81c51d720e7"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/2 HTTP/1.1

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1